# Generated by Django 4.2.2 on 2023-06-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=25)),
                ('address_from', models.CharField(max_length=45)),
                ('address_to', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=40)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='delivery.delivery')),
            ],
        ),
    ]
