# Generated by Django 4.2.2 on 2023-06-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='content',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
