version: "3"

services:
  db:
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
    image: postgres:12
    restart: always
    volumes:
      #- ./tmp/app/mysqld:/var/run/mysqld
      - pgdata:/var/lib/posgresql/data
      #- db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: ${DATABASE_USER}
      # You can use whatever password you like
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    expose:
      # Opens port 3306 on the container
      - ${DATABASE_PORT}

  web:
    build: .
    # command: python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${SERVER_PORT}"
    volumes:
      - .:/code
      #- ./tmp/app/mysqld:/run/mysqld
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      # - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - db

volumes:
  pgdata:
